#Build settings
markdown: kramdown
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-target-blank # automatically sets any external URL to open in a new tab

#Customziatin for DORA project
title: DORA
description: Dataflow-Oriented Robotics Architecture
